name: bart_eval
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch==1.9.1+cu111
    - torchvision==0.10.1+cu111
    - torchaudio==0.9.1
    - -f https://download.pytorch.org/whl/torch_stable.html
    - transformers==4.14.1
    - pytorch-ignite==0.4.9
    - tensorboardX
    - accelerate
